#!/bin/sh
echo 
echo "change $1 to $2"
echo
# find the parameter that you want to change, and then change it
sed -i 's/\('$1'=\).*/\1'$2'/' /mnt/card/Config.ini

# save the new paramter
sync

# find the thread: single-board-test's PID
#ps -eaf | grep single-board-test | awk '{print $2}' |xargs kill -9
pkill single-board-test

# finish, and wait
echo "the parameter is changed, and just wait the single-board-test thread start up for several seconds"
echo 
